name: Deploy Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.USER_TOKEN }}" --password-stdin

      - name: Set Docker image tag
        id: vars
        run: echo "IMAGE_TAG=${{ secrets.USER_TOKEN }}/ci_bankingsystem:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ env.ghcr.io/SSDLC-UR-20251/Bankingsystem:latest }} .
  
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.ghcr.io/SSDLC-UR-20251/Bankingsystem:latest }}

